#
# Makefile for the fingerprint drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_FINGERPRINT_EGISTEC_FPS_MMI)	+= ets_fps_mmi/
obj-$(CONFIG_FINGERPRINT_FPC_TEE_MMI)	+= fpc_fps_mmi/
