name: Build kernel

on: 
  push:


jobs:

  build:
    runs-on: ubuntu-20.04

   
    steps:
    - name: Checkout
      uses: actions/checkout@main
      
    - name: Start
      run: |
        chmod a+x compile.sh
        ./compile.sh
